### ISSUE TITLE
Missing Nuget Packages / Config File for Visual Studio

### ISSUE THREAD

**Issue by macmillanr** [stellarbear/YaraSharp#2]
Trying to recompile the project to target .net 3.5, but can't locate four dependencies and not sure where to find them after searching everywhere. 

Is there a nuget service I should be using to find:
YARA.Jansson.x64 / YARA.Jansson.x86
YARA.OpenSSL.x64 / YARA.OpenSSL.x86

Or are these just normal Jansson/OpenSLL projects that have been renamed/recompiled?

**Comment by macmillanr** [comment]
ok - can close - (but putting solution here). 

I was searching through the VT yara project and found a nuget config file that isn't in this project. Incase anyone tries to recompile in VS, you need to add two new package sources:

Name: YARA.OpenSSL
Source: https://ci.appveyor.com/nuget/openssl-oaib8n7lvvtp
Name: YARA.Jansson
https://ci.appveyor.com/nuget/jansson-41we82mn284d

**Comment by stellarbear** [comment]
Added deps folder in case anyone has trouble in locating Jansson and OpenSSL
