### ISSUE TITLE
Memory Leaks - Instance.cpp

### ISSUE THREAD

**Issue by adamsh25** [stellarbear/YaraSharp#5]
Hi,
in Instance.cpp an exception can be thrown, as a result the  "delete PScanner;" will not be called
adding try...catch...finally... or try...finally... should fix the issue

 in case of an exception the YSScanner is not disposed

```
	List<YSMatches^>^ YSInstance::ScanProcess(int pID, YSRules^ rules, Dictionary<String^, Object^>^ externalVariables, int timeout)
	{
		YSScanner^ PScanner = gcnew YSScanner(rules, externalVariables, timeout);
		try{
			List<YSMatches^>^ results = PScanner->ScanProcess(pID);
			return results;
		}
		catch (System::Exception^ e){
			throw e;
		}
		finally{
			delete PScanner;
		}

	}
```

**Comment by adamsh25** [comment]
also in SetScannerCallback, SetCompilerCallback, 
after each GCHandle::Alloc(+=) you have to free the allocated delegate (-=)
- I suggest you to release the handle when calling the ~Destructor
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandle.alloc?view=netframework-4.7.2

**Comment by stellarbear** [comment]
I apologize for such a big delay in response.
I will investigate this in the coming weekdays

**Comment by stellarbear** [comment]
Seems reasonable. Will fix that on Process & Memory & File methods in 1.3.1
