### ISSUE TITLE
[enhancement]New function

### ISSUE THREAD

**Issue by nblog** [stellarbear/YaraSharp#9]
I added two new functions according to my own needs.
★1. CompileFromString -> Instance.cpp
2. CompileFromFile -> Instance.cpp
I hope it helps :)

[Instance.h](https://1drv.ms/u/s!At5vghbk6PuShwmEmBIcT_8blUbn) [Instance.cpp](https://1drv.ms/u/s!At5vghbk6PuShwpZxOxSbw2UFDjN)
[Compiler.h](https://1drv.ms/u/s!At5vghbk6PuShwvCs_HthcV4t3LM) [Compiler.cpp](https://1drv.ms/u/s!At5vghbk6PuShwilvCrtaOXmPu20)

**Comment by stellarbear** [comment]
Hello, thank you for your interest!

You can make a PR or will have to wait once i will have time for this
